name: secrect and atifacts

on:
  push:
    branches:
      - master

jobs:
  secret-and-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Check if secret is set
        run: |
          if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is set: false"
          fi

      - name: generate log file
        run: |
          echo "This is a log message" > log.txt
          echo "Another log message" >> log.txt
          echo "Log file generated: log.txt"
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: log.txt
