name: GitHub Actions Demo

on: [push]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "Hello from GitHub Actions!"
